workflows:
  flutter-android:
    name: CI/CD with Shorebird + Firebase
    environment:
      flutter: stable
      vars:
        FIREBASE_TOKEN: Encrypted(...)
        SHOREBIRD_TOKEN: Encrypted(...)
    scripts:
      - name: Build APK
        script: flutter build apk --release

      - name: Shorebird OTA Release
        script: |
          shorebird login --api-token $SHOREBIRD_TOKEN
          shorebird release android

      - name: Firebase App Distribution
        script: |
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk ^
            --app legy-79c27 ^
            --token $FIREBASE_TOKEN ^
            --groups "testers"
