trigger:
  events:
    - push
  branch_patterns:
    - pattern: main
      include: true

workflows:
  flutter-android:
    name: Firebase CI/CD (APK + Shorebird)
    environment:
      flutter: 3.29.3
      groups:
        - testers
    cache:
      cache_paths:
        - $HOME/.gradle/caches
        - $HOME/.gradle/wrapper

    scripts:
      - name: Install Shorebird CLI
        script: |
          curl https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh -sSf | bash
          export PATH="$HOME/.shorebird/bin:$PATH"

      - name: Authenticate Shorebird
        script: |
          export PATH="$HOME/.shorebird/bin:$PATH"
          shorebird login:ci --access-token="$SHOREBIRD_ACCESS_TOKEN"

      - name: Setup the keystore
        script: |
          echo $CM_KEYSTORE | base64 --decode > /tmp/keystore.jks
          cat > "$CM_BUILD_DIR/android/key.properties" <<EOF
          storePassword=$CM_KEYSTORE_PASSWORD
          keyPassword=$CM_KEY_PASSWORD
          keyAlias=$CM_KEY_ALIAS
          storeFile=/tmp/keystore.jks
          EOF

      - name: Bump versionCode and versionName
        script: |
          cd $CM_BUILD_DIR
          VERSION_CODE=$(date +%s)
          MAJOR=1
          MINOR=1
          PATCH=9
          VERSION_NAME="$MAJOR.$MINOR.$PATCH"
          echo "Setting versionCode=$VERSION_CODE and versionName=$VERSION_NAME"
          sed -i.bak -E "s/versionCode [0-9]+/versionCode $VERSION_CODE/" android/app/build.gradle
          sed -i.bak -E "s/versionName \".*\"/versionName \"$VERSION_NAME\"/" android/app/build.gradle

      - name: Get Flutter packages
        script: |
          cd $CM_BUILD_DIR
          flutter pub get

      - name: Build APK with Shorebird
        script: |
          export PATH="$HOME/.shorebird/bin:$PATH"
          cd $CM_BUILD_DIR
          shorebird release android --artifact=apk --flavor=release

      - name: Authenticate Firebase CLI
        script: |
          echo $FIREBASE_SERVICE_ACCOUNT | base64 --decode > /tmp/firebase-service-account.json
          export GOOGLE_APPLICATION_CREDENTIALS=/tmp/firebase-service-account.json

      - name: Distribute via Firebase App Distribution
        script: |
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
            --app 1:540049131134:android:74e974643a939bc2317a2f \
            --groups "testers" \
            --release-notes-file android/release_notes.txt

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

    publishing:
      email:
        recipients:
          - msallemnacim@gmail.com
        notify:
          success: true
          failure: true
