workflows:
  flutter-android:
    name: Firebase CI/CD (APK) + Shorebird OTA
    environment:
      flutter: 3.29.3
      groups:
        - testers
    cache:
      cache_paths:
        - $HOME/.gradle/caches
        - $HOME/.gradle/wrapper  
    scripts:
      - name: Setup the keystore
        script: |
          echo $CM_KEYSTORE | base64 --decode > /tmp/keystore.jks
          cat > "$CM_BUILD_DIR/android/key.properties" <<EOF
          storePassword=$CM_KEYSTORE_PASSWORD
          keyPassword=$CM_KEY_PASSWORD
          keyAlias=$CM_KEY_ALIAS
          storeFile=/tmp/keystore.jks
          EOF

      - name: Get Flutter packages
        script: |
          cd $CM_BUILD_DIR
          flutter pub get

      - name: Build APK
        script: |
          flutter build apk --release

      - name: Authenticate Firebase CLI
        script: |
          echo $FIREBASE_SERVICE_ACCOUNT | base64 --decode > /tmp/firebase-service-account.json
          export GOOGLE_APPLICATION_CREDENTIALS=/tmp/firebase-service-account.json

      - name: Distribute via Firebase App Distribution
        script: |
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
            --app 1:540049131134:android:74e974643a939bc2317a2f \
            --groups "testers"

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

    publishing:
      email:
        recipients:
          - msallemnacim@gmail.com
        notify:
          success: true
          failure: true
