workflows:
  flutter-android:
    name: Firebase CI/CD (APK) + Shorebird OTA
    environment:
      flutter: 3.29.3
      groups:
        - testers
    scripts:
      - name: Setup the keystore
        script: |
          echo $CM_KEYSTORE | base64 --decode > /tmp/keystore.jks
          cat > "$CM_BUILD_DIR/android/key.properties" <<EOF
          storePassword=$CM_KEYSTORE_PASSWORD
          keyPassword=$CM_KEY_PASSWORD
          keyAlias=$CM_KEY_ALIAS
          storeFile=/tmp/keystore.jks
          EOF

      - name: Get Flutter packages
        script: |
          cd $CM_BUILD_DIR
          flutter pub get

      - name: Build AAB
        script: |
          flutter build appbundle --release

      - name: Build Flutter APK
        script: |
          flutter clean
          flutter pub get
          flutter build apk --release

      - name: Shorebird OTA Release
        script: |
          shorebird login --api-token $SHOREBIRD_TOKEN
          shorebird release android

      - name: Distribute via Firebase App Distribution
        script: |
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
            --app 1:540049131134:android:74e974643a939bc2317a2f \
            --token $FIREBASE_TOKEN \
            --groups "testers"

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

    publishing:
      email:
        recipients:
          - msallemnacim@gmail.com
        notify:
          success: true
          failure: true
