name: testing
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  expand: ^1.2.0
  flutter_advanced_switch: ^3.1.0
  flutter_bloc: ^9.0.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  fluttertoast: ^8.2.12
  gap: ^3.0.1
  go_router: ^14.8.1
  pinput: ^5.0.1
  shared_preferences: ^2.5.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-100.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-200.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-300.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-400.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-500.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-600.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-700.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-800.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-900.ttf
          weight: 900